backend:
  name: github
  branch: main
  open_authoring: true
  repo: trailangeles/trailangeles
  auth_scope: repo
media_folder: "src/static/img"
public_folder: "/static/img"

local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Places and Orgs"
    name: "places-and-orgs"
    extension: "json"
    editor:
      preview: false
    files:
      - label: "Organizations"
        file: "src/_data/orgs.json"
        name: "organizations"
        widget: "object"
        collapsed: false
        fields:
          - label: Organizations
            name: organizations
            widget: list
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  hint: "URL for this org e.g. lowe-lifes. lowercase, hyphenated, no spaces or special characters.",
                  widget: string,
                  required: true,
                }
              - { label: Contact Name, name: contactName, widget: string }
              - { label: Contact Email, name: contactEmail, widget: string }
              - { label: Photo, name: photo, widget: file }
              - { label: Website, name: website, widget: string }
              - {
                  label: Facebook,
                  name: facebook,
                  widget: string,
                  required: false,
                }
              - {
                  label: Instagram,
                  name: instagram,
                  widget: string,
                  required: false,
                }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  required: false,
                }
              - { label: ID, name: id, widget: id }
              - {
                  label: Places,
                  name: places,
                  widget: relation,
                  collection: places-and-orgs,
                  file: "places",
                  valueField: places.*.id,
                  displayFields: [places.*.name],
                  searchFields: [places.*.name],
                  multiple: true,
                  required: false,
                  options_length: 999,
                  hint: "List of places this organization maintains. They will show up on the organization page",
                }
              - {
                  label: Sortable Filters,
                  name: filters,
                  widget: relation,
                  collection: events-and-filters,
                  file: "filters",
                  valueField: filters.*.id,
                  displayFields: [filters.*.name],
                  searchFields: [filters.*.name],
                  multiple: true,
                  required: false,
                  options_length: 999,
                  hint: "List of tags for this group that users can filter with in the UI",
                }
      - label: "Points"
        file: "src/_data/points.json"
        name: "points"
        widget: "object"
        collapsed: false
        fields:
          - label: Points
            name: points
            widget: list
            collapsed: false
            fields:
              - {
                  label: Address,
                  name: address,
                  widget: string,
                  required: false,
                }
              - { label: Phone, name: phone, widget: string, required: false }
              - { label: Hours, name: hours, widget: string, required: false }
              - { label: Notes, name: notes, widget: string, required: false }
              - {
                  label: Site Type,
                  name: siteType,
                  widget: string,
                  required: false,
                }
              - { label: Marker Pop-Up Title, name: name, widget: string }
              - {
                  label: Marker Pop-Up Description,
                  name: description,
                  widget: string,
                }
              - { label: Location, name: location, widget: map }
              - {
                  label: Mapbox Maki Icon Name,
                  name: maki,
                  widget: string,
                  required: false,
                  hint: "View them here https://labs.mapbox.com/maki-icons/",
                }
              - { label: ID, name: id, widget: id }
      - label: "Places"
        file: "src/_data/places.json"
        name: "places"
        widget: "object"
        collapsed: false
        fields:
          - label: Places
            name: places
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  hint: "URL for this slug e.g. mt-wilson. lowercase, hyphenated, no spaces or special characters.",
                  widget: string,
                  required: true,
                }
              - { label: ID, name: id, widget: id }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  required: false,
                }
              - {
                  label: OsmWayId,
                  name: osmwayid,
                  widget: string,
                  required: false,
                  hint: "The numeric id at the end of e.g. https://www.openstreetmap.org/way/178426128, this will import the tags for that way on osm every time the site builds",
                }
              - {
                  label: OsmTags,
                  name: osmtags,
                  widget: hidden,
                  required: false,
                }
              - {
                  label: "Open/Closed Status",
                  name: "status",
                  widget: "boolean",
                  required: true,
                  default: true,
                }
              - {
                  label: Points,
                  name: points,
                  widget: relation,
                  collection: places-and-orgs,
                  file: "points",
                  valueField: points.*.id,
                  displayFields: [points.*.name],
                  searchFields: [points.*.name],
                  multiple: true,
                  required: false,
                  options_length: 999,
                  hint: "List of points associated with this place. They will show up on the place map as clickable icons",
                }
              - {
                  label: Sortable Filters,
                  name: filters,
                  widget: relation,
                  collection: events-and-filters,
                  file: "filters",
                  valueField: filters.*.id,
                  displayFields: [filters.*.name],
                  searchFields: [filters.*.name],
                  multiple: true,
                  required: false,
                  options_length: 999,
                  hint: "List of tags for this place that users can filter with in the UI",
                }
  - label: "Events and Filters"
    name: "events-and-filters"
    extension: "json"
    editor:
      preview: false
    files:
      - file: "src/_data/sortablefilters.json"
        label: "Sortable Filters"
        name: "filters"
        widget: "object"
        collapsed: false
        fields:
          - label: Sortable Filters
            name: filters
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: ID, name: id, widget: id }
      - file: "src/_data/events.json"
        label: "Events"
        name: "events"
        widget: "object"
        collapsed: false
        fields:
          - label: Events
            name: events
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Date, name: date, widget: datetime }
              - { label: Description, name: description, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: ID, name: id, widget: id }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
      - label: "Alert"
        name: "alert"
        file: "src/_data/alert.yaml"
        fields:
          - { label: Alert Text, name: text, widget: string }
          - { label: Alert Status, name: status, widget: boolean }
          - { label: Alert Link, name: string, widget: string }
          - { label: Alert Link Status, name: linkStatus, widget: boolean }
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: ID, name: id, widget: id }
